DROP TABLE IF EXISTS `autoplay`;

CREATE TABLE `autoplay` (
	`no`	BIGINT	NOT NULL AUTO_INCREMENT PRIMARY KEY	COMMENT 'PK',
	`id`	VARCHAR(64)	NOT NULL	COMMENT 'UK',
	`username`	VARCHAR(100)	NOT NULL	COMMENT '사용자ID',
	`content_name`	TEXT	NOT NULL	COMMENT '컨텐츠명(영화명)',
	`std_time`	TIMESTAMP	NOT NULL	COMMENT '시작시간',
	`end_time`	TIMESTAMP	NOT NULL	COMMENT '종료시간',
	`play_time`	BIGINT	NOT NULL	COMMENT '시청시간( ms, 밀리초 )',
	`created_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '등록일자',
	`updated_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '수정일자'
) COMMENT '오토플레이';
