DROP TABLE IF EXISTS `click`;

CREATE TABLE `click` (
	`no`	BIGINT	NOT NULL AUTO_INCREMENT PRIMARY KEY	COMMENT 'PK',
	`id`	VARCHAR(64)	NOT NULL	COMMENT 'UK',
	`username`	VARCHAR(100)	NOT NULL	COMMENT '사용자ID',
	`content_name`	TEXT	NOT NULL	COMMENT '컨텐츠명(영화명)',
	`created_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '등록일자',
	`updated_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '수정일자'
) COMMENT '클릭';