DROP TABLE IF EXISTS `use_time`;

CREATE TABLE `use_time` (
	`no`	BIGINT	NOT NULL AUTO_INCREMENT PRIMARY KEY	COMMENT 'PK',
	`id`	VARCHAR(64)	NOT NULL	COMMENT 'UK',
	`username`	VARCHAR(100)	NOT NULL	COMMENT '사용자ID',
	`std_time`	TIMESTAMP	NOT NULL	COMMENT '시작시간',
	`end_time`	TIMESTAMP	NOT NULL	COMMENT '종료시간',
	`login_time`	TIMESTAMP	NOT NULL	COMMENT '로그인시간',
	`use_time`	BIGINT	NOT NULL	COMMENT '잔류시간( ms, 밀리초 )',
	`created_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '등록일자',
	`updated_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '수정일자'
) COMMENT '잔류시간';
