-- Active: 1731384027892@@127.0.0.1@3306@autoplay
-- user
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `NO` bigint NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `ID` VARCHAR(64) NOT NULL COMMENT 'UK',
  `USERNAME` varchar(100) NOT NULL COMMENT '아이디',
  `PASSWORD` varchar(200) NOT NULL COMMENT  '비밀번호',
  `GENDER` varchar(100) NOT NULL COMMENT '성별',
  `BIRTH` timestamp COMMENT '생년월일',
  `CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일자',
  `UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일자',
  `ENABLED` int DEFAULT 1 COMMENT '사용여부',
  PRIMARY KEY (`NO`)
) COMMENT='회원';